version = 1

[[analyzers]]
name = "rust"
enabled = true

[analyzers.meta]
# Disable opinionated style lints
# single_match suggests converting match with one arm to if-let
# We prefer match statements as they're easier to extend
# new_without_default suggests using T::default() instead of T::new()
# We prefer the idiomatic String::new() and Vec::new() convention
exclude_patterns = [
    "clippy::single_match",
    "clippy::single_match_else",
    "clippy::new_without_default",
]
