title: Lemma
description: A language that means business.
theme: jekyll-theme-cayman
show_downloads: false
baseurl: "/Lemma"
url: "https://benrogmans.github.io"

# GitHub metadata
repository: benrogmans/Lemma
github:
  is_project_page: true

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Navigation
nav_links:
  - title: Home
    url: /
  - title: Language Guide
    url: /index.html
  - title: Reference
    url: /REFERENCE.html
  - title: Examples
    url: /examples/
  - title: GitHub
    url: https://github.com/benrogmans/lemma

# SEO
lang: en
author: Ben Rogmans

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

